databases:
  - name: smartsaver
    databaseName: smartsaver
    user: smartsaver_user

services:
  - type: web
    name: SmartSaver
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smartsaver
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false